Style updates to improve SPDF compliance
jklenzing/ops_reach pull request #15
Opened 2023-01-31 22:37 UTC by jklenzing

# Description

Updates meta data and file naming conventions to improve compatibility with SPDF systems.

## Type of change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Inspection of files

2023-02-02 19:30 UTC, jklenzing commented
TODO:
- [ ] add download support to get all files
- [ ] Update val_max of nan with statistically derived values

2023-04-13 18:46 UTC, jklenzing commented on ops_reach/instruments/methods/reach.py
> +    """Download data (placeholder). Doesn't do anything.
```suggestion
    """Download data from zenodo.
```

2023-04-13 18:47 UTC, jklenzing commented on ops_reach/instruments/aero_reach.py
> +    '101', '105', '113', '133', '135'
update!

2023-06-02 14:26 UTC, JonathonMSmith requested changes
these two hyphens are unicode, so we should change them

2023-06-02 14:26 UTC, JonathonMSmith commented on ops_reach/instruments/methods/reach.py
>                                                        '1 – protons, 2-electrons',
```suggestion
                                                      '1-protons, 2-electrons',
```

2023-06-02 14:26 UTC, JonathonMSmith commented on ops_reach/instruments/methods/reach.py
>                                                        '1 – protons, 2-electrons',
```suggestion
                                                      '1-protons, 2-electrons',
```

2023-06-15 15:09 UTC, merged